version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data

  # Backend
  agent-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-backend
    ports:
      - "8080:8080"
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RAILWAY_TCP_PROXY_DOMAIN: ${RAILWAY_TCP_PROXY_DOMAIN}
      RAILWAY_TCP_PROXY_PORT: ${RAILWAY_TCP_PROXY_PORT}
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      - postgres