spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    url: jdbc:postgresql://localhost:5432/my-agent-postgres
    username: agent
    password: agent123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host:  ${RAILWAY_TCP_PROXY_DOMAIN}
    port: ${RAILWAY_TCP_PROXY_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    template:
      reply-timeout: 5000

server:
  port: 8080
